// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// s2polygon
List s2polygon(List x, bool validate);
RcppExport SEXP s2_s2polygon(SEXP xSEXP, SEXP validateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type validate(validateSEXP);
    rcpp_result_gen = Rcpp::wrap(s2polygon(x, validate));
    return rcpp_result_gen;
END_RCPP
}
