// This file was automatically generated by
// `tools::package_native_routine_registration_skeleton`

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME: 
Check these declarations against the C/Fortran source code.
*/

/* .Call calls */
extern SEXP s2_S2Cap_area(SEXP);
extern SEXP s2_S2Cap_contains_point(SEXP, SEXP);
extern SEXP s2_S2CapFromAxisHeight(SEXP, SEXP);
extern SEXP s2_S2Cell_grid_centers(SEXP);
extern SEXP s2_S2Cell_vertices_from_point(SEXP, SEXP);
extern SEXP s2_S2Cell_vertices_from_token(SEXP);
extern SEXP s2_S2CellId_ToPoint(SEXP);
extern SEXP s2_S2CellId_ToString(SEXP);
extern SEXP s2_S2CellIdFromPoint(SEXP, SEXP);
extern SEXP s2_S2Covering_internal(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP s2_S2Point_interpolate(SEXP, SEXP);
extern SEXP s2_S2Polygon_contains_point(SEXP, SEXP, SEXP);
extern SEXP s2_S2Polygon_intersection(SEXP, SEXP);
extern SEXP s2_S2Polygon_union(SEXP, SEXP);
extern SEXP s2_S2PolygonBuild(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP s2_S2Polyline_dist(SEXP, SEXP);
extern SEXP s2_S2Cap_GetRectBound(SEXP);
extern SEXP s2_S2LatLngRect(SEXP, SEXP);
extern SEXP s2_S2LatLngRect_area(SEXP);

static const R_CallMethodDef CallEntries[] = {
  {"s2_S2Cap_area",                 (DL_FUNC) &s2_S2Cap_area,                 1},
  {"s2_S2Cap_contains_point",       (DL_FUNC) &s2_S2Cap_contains_point,       2},
  {"s2_S2CapFromAxisHeight",        (DL_FUNC) &s2_S2CapFromAxisHeight,        2},
  {"s2_S2Cell_grid_centers",        (DL_FUNC) &s2_S2Cell_grid_centers,        1},
  {"s2_S2Cell_vertices_from_point", (DL_FUNC) &s2_S2Cell_vertices_from_point, 2},
  {"s2_S2Cell_vertices_from_token", (DL_FUNC) &s2_S2Cell_vertices_from_token, 1},
  {"s2_S2CellId_ToPoint",           (DL_FUNC) &s2_S2CellId_ToPoint,           1},
  {"s2_S2CellId_ToString",          (DL_FUNC) &s2_S2CellId_ToString,          1},
  {"s2_S2CellIdFromPoint",          (DL_FUNC) &s2_S2CellIdFromPoint,          2},
  {"s2_S2Covering_internal",        (DL_FUNC) &s2_S2Covering_internal,        6},
  {"s2_S2Point_interpolate",        (DL_FUNC) &s2_S2Point_interpolate,        2},
  {"s2_S2Polygon_contains_point",   (DL_FUNC) &s2_S2Polygon_contains_point,   3},
  {"s2_S2Polygon_intersection",     (DL_FUNC) &s2_S2Polygon_intersection,     2},
  {"s2_S2Polygon_union",            (DL_FUNC) &s2_S2Polygon_union,            2},
  {"s2_S2PolygonBuild",             (DL_FUNC) &s2_S2PolygonBuild,             6},
  {"s2_S2Polyline_dist",            (DL_FUNC) &s2_S2Polyline_dist,            2},
  {"s2_S2Cap_GetRectBound",         (DL_FUNC) &s2_S2Cap_GetRectBound,         1},
  {"s2_S2LatLngRect",               (DL_FUNC) &s2_S2LatLngRect,               2},
  {"s2_S2LatLngRect_area",          (DL_FUNC) &s2_S2LatLngRect_area,          1},
  {NULL, NULL, 0}
};

void R_init_s2(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
