# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interval_test <- function(x, a, b) {
    .Call('s2_interval_test', PACKAGE = 's2', x, a, b)
}

